[package]
name = "basalt_inscription"
version = "0.1.0"
edition = "2021"

[lib]
name = "basalt_inscription"
crate-type = ["cdylib", "lib"]

[features]
no-entrypoint = []

[dependencies]
anchor-lang = "0.29.0"
solana-program = "=1.18.26"

[profile.release]
opt-level = "s"
panic = "abort"
codegen-units = 1
lto = "thin"