[toolchain]
anchor_version = "0.29.0"

[features]
resolution = true
skip-lint = false

[programs.devnet]
basalt_inscription = "GRJr1pdTLEqpWRiSvvWCLZViKqxD7tiMYpPUEjUUgZin"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "cargo test-bpf"


